### ISSUE TITLE
Error "{remotePath} is not found."

### ISSUE THREAD

**Issue by 6sRyuSK** [yushimatenjin/playcanvas-node#5]
[src/playcanvas-api.ts:52 updateAssets](https://github.com/yushimatenjin/playcanvas-node/blob/28a8c4668076408857f078277ad8a16031dc4ac9/src/playcanvas-api.ts#L52) 
にてassetsListを取得しdevDirを定義する際、
[Assets - List assets API](https://developer.playcanvas.com/en/user-manual/api/asset-list/)のアセット取得上限がデフォルトで16に設定されているため
プロジェクトのアセットが16個以上ある場合、
正確なremotePathを入力していてもエラーが発生する可能性がある事を確認しました。

また`/projects/${projectId}/assets?branchId=${branchId}&limit=32`このようにクエリを設定すると取得上限を設定できるみたいです
https://developer.playcanvas.com/en/user-manual/api/#response-format

**Comment by 6sRyuSK** [comment]
プロジェクトによっては何百個のアセットを扱うこともあると思うのでremotePathをassetNameではなくassetIdを設定してあげてGet Assetを使ったほうがスマートなのかなと思いました

**Comment by yushimatenjin** [comment]
確認が遅くなり申し訳ありません！

APIの詳細ありがとうございます、チェックいたします！

**Comment by yushimatenjin** [comment]
https://github.com/yushimatenjin/playcanvas-node/blob/da850d0eaddc49fd60ecb7a44825cf11f321b44f/src/endpoints.ts#L20

コード


```javascript
//変更後
endpointUrlJoin`/projects/${projectId}/assets?branchId=${branchId}&limit=${Number.MAX_SAFE_INTEGER}`

//test.js
const assets =  await playcanvas.listAssets();
console.log("Assets Length = ",assets.length)
```
実行結果
![ScreenShot 256](https://user-images.githubusercontent.com/39250588/84220354-873bf700-ab0d-11ea-8379-f225757cdfe2.jpg)

上記の行にLimitをAsset数より大きな整数値で置いてみましたところ95個のアセットを取得ができました。

ドキュメントを見る限り、LimitとSkipが設定できるようなのでできればドキュメントに沿った実装をしたいと考えておりますが、果たしてPagenationをする意味はあるのだろうか...

**Comment by yushimatenjin** [comment]
一つマージをしてみました。
https://github.com/yushimatenjin/playcanvas-node/pull/6

> プロジェクトによっては何百個のアセットを扱うこともあると思うのでremotePathをassetNameではなくassetIdを設定してあげてGet Assetを使ったほうがスマートなのかなと思いました

こちらも今後修正いたします！
